"""Render benchmark reports as Markdown or JSON."""

from __future__ import annotations

import json

from .corpora import CorpusFit
from .runner import BenchReport, CorpusResult


def _pct(x: float) -> str:
    return f"{x * 100:.1f}%"


def _row_md(r: CorpusResult) -> str:
    if r.corpus.fit is CorpusFit.CEILING_TEST:
        recall_cell = f"{_pct(r.recall)} _(ceiling)_"
    else:
        recall_cell = _pct(r.recall)
    fpr_cell = _pct(r.false_positive_rate) if r.expected_negative else "-"
    return (
        f"| `{r.corpus.name}` | {r.corpus.fit.value} | "
        f"{r.total} | {r.expected_positive} / {r.expected_negative} | "
        f"{recall_cell} | {fpr_cell} | {r.missed_positive} |"
    )


def render_markdown(report: BenchReport) -> str:
    lines: list[str] = []
    lines.append("# Ward benchmark report")
    lines.append("")
    lines.append(f"_Generated: {report.generated_at.strftime('%Y-%m-%d %H:%M UTC')}_  ")
    lines.append(f"_Ward version: `{report.ward_version}`_  ")
    lines.append(f"_Fail threshold: `{report.fail_on.value}`_")
    lines.append("")
    lines.append("## Headline numbers")
    lines.append("")
    lines.append(f"- In-scope recall: **{_pct(report.overall_recall)}**")
    lines.append(f"- In-scope false-positive rate: **{_pct(report.overall_false_positive_rate)}**")
    lines.append("")
    lines.append("## Per-corpus results")
    lines.append("")
    lines.append("| Corpus | Fit | Rows | Pos / Neg | Recall | FPR | Missed |")
    lines.append("|--------|-----|------|-----------|--------|-----|--------|")
    for r in report.results:
        lines.append(_row_md(r))
    lines.append("")
    lines.append("Legend:")
    lines.append("- **Pos / Neg**: number of expected-injection rows / expected-benign rows")
    lines.append("- **Recall**: of the injection rows, what fraction did Ward flag")
    lines.append("- **FPR**: of the benign rows, what fraction did Ward incorrectly flag")
    lines.append("- **Missed**: injection rows Ward let through")
    lines.append(
        "- **Ceiling**: the corpus tests a known out-of-scope class; "
        "a low recall here is the honest answer, not a regression"
    )
    lines.append("")
    lines.append("## Rules that fired (by category)")
    lines.append("")
    for r in report.results:
        if not r.fired_categories:
            continue
        lines.append(f"### `{r.corpus.name}`")
        lines.append("")
        for cat, count in sorted(r.fired_categories.items(), key=lambda kv: (-kv[1], kv[0])):
            lines.append(f"- `{cat}`: {count}")
        lines.append("")
    lines.append("## Corpora cited")
    lines.append("")
    for r in report.results:
        lines.append(
            f"- **{r.corpus.name}** ({r.corpus.license}): {r.corpus.description} "
            f"Source: <{r.corpus.upstream_url}>"
        )
    lines.append("")
    lines.append("## Honest caveats")
    lines.append("")
    lines.append(
        "These numbers are from bundled 50-row samples of each upstream "
        "corpus, redistributed under each upstream's MIT or Apache 2.0 licence. "
        "Run `ward bench --download <corpus>` to score against the full sets "
        "(coming in v0.2). The samples are a smoke test, not a final word."
    )
    lines.append("")
    lines.append(
        "The ceiling-test corpus (`advbench_harmful_behaviors`) intentionally "
        "tests an out-of-scope class. A low recall there is by design; see "
        "`SECURITY.md` for the full list of known limitations."
    )
    lines.append("")
    lines.append("_Generated by `ward bench`._")
    return "\n".join(lines)


def render_json(report: BenchReport) -> str:
    payload = {
        "tool": "ward",
        "version": report.ward_version,
        "generated_at": report.generated_at.isoformat(),
        "fail_on": report.fail_on.value,
        "summary": {
            "overall_recall_in_scope": report.overall_recall,
            "overall_false_positive_rate_in_scope": report.overall_false_positive_rate,
        },
        "corpora": [
            {
                "name": r.corpus.name,
                "fit": r.corpus.fit.value,
                "license": r.corpus.license,
                "upstream_url": r.corpus.upstream_url,
                "total": r.total,
                "expected_positive": r.expected_positive,
                "expected_negative": r.expected_negative,
                "detected_positive": r.detected_positive,
                "detected_negative": r.detected_negative,
                "missed_positive": r.missed_positive,
                "recall": r.recall,
                "precision": r.precision,
                "false_positive_rate": r.false_positive_rate,
                "fired_categories": r.fired_categories,
            }
            for r in report.results
        ],
    }
    return json.dumps(payload, indent=2, ensure_ascii=False)
